### ISSUE TITLE
Add change password in profile section

### ISSUE THREAD

**Issue by Adnan-Jindani** [Adnan-Jindani/cryptoPlay#37]

**Comment by Adnan-Jindani** [comment]
@sum1there is working on it right now
Do the main page first and then we'll continue on this..

**Comment by PyNonOfReplit** [comment]
Ok cool

**Comment by sum1there** [comment]
i'm confused on the issue. 
without a description, i don't know what the actual problem is. but there are two things that i'm getting from the title; either:
- you need to migrate the page into the profile section
- you need to make the password check actually work
- or both

if you need the password check to actually work, that's simple enough to do. if there's a profile section that i'm somehow missing, please direct me in the right direction.

**Comment by Adnan-Jindani** [comment]
Wait I'll explain @sum1there

**Comment by Adnan-Jindani** [comment]
Development on this project isn't active from now onwards..
